# Generated by Django 4.1.5 on 2023-01-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_rating', models.PositiveIntegerField()),
                ('session_notes', models.TextField()),
            ],
        ),
    ]
