# Generated by Django 4.1.5 on 2023-01-25 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily_sessions', '0001_initial'),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='owner_of_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='session_trades',
            field=models.ManyToManyField(related_name='daily_sessions', to='trades.trade'),
        ),
    ]
