# Generated by Django 4.1.4 on 2022-12-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_owner_of_trade'),
        ('daily_sessions', '0002_alter_session_owner_of_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_trades',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_sessions', to='trades.trade'),
        ),
    ]
