# Generated by Django 4.1.4 on 2022-12-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_trade_mistakes'),
        ('daily_sessions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_trades',
        ),
        migrations.AddField(
            model_name='session',
            name='session_trades',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='daily_sessions', to='trades.trade'),
        ),
    ]
