# Generated by Django 4.1.4 on 2022-12-11 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opened', models.DateField()),
                ('date_closed', models.DateField(blank=True, default=None, null=True)),
                ('asset_class', models.CharField(choices=[(None, 'Select Asset'), ('stocks', 'Stocks'), ('crypto', 'Crypto'), ('forex', 'Forex'), ('futures', 'Futures'), ('options', 'Options'), ('bonds', 'Bonds')], default=None, max_length=7)),
                ('trade_type', models.CharField(choices=[(None, 'Select Type'), ('DT', 'Day Trade'), ('ST', 'Swing'), ('LT', 'Long Term')], default=None, max_length=2)),
                ('side', models.CharField(choices=[(None, 'Select Type'), ('long', 'Long'), ('short', 'Short')], default=None, max_length=5)),
                ('symbol', models.CharField(max_length=15)),
                ('timeframe', models.CharField(choices=[(None, 'Select Timeframe'), ('1', '1 min'), ('2', '2 min'), ('3', '3 min'), ('5', '5 min'), ('10', '10 min'), ('15', '15 min'), ('30', '30 min'), ('60', '60 min'), ('1 hour', '1 hour'), ('4 hour', '4 hour'), ('daily', 'Daily'), ('weekly', 'Weekly')], default=None, max_length=10)),
                ('target', models.FloatField(blank=True, default=None, null=True)),
                ('stoploss', models.FloatField(blank=True, default=None, null=True)),
                ('expected_r', models.FloatField(blank=True, default=None, null=True)),
                ('avg_buy_price', models.FloatField(blank=True, default=None, null=True)),
                ('setup', models.CharField(max_length=100)),
                ('mistakes', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('owner_of_trade', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
