# Generated by Django 4.1.4 on 2022-12-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opened', models.DateField()),
                ('date_closed', models.DateField(blank=True, default=None, null=True)),
                ('asset_class', models.CharField(choices=[(None, 'Select Asset'), ('stocks', 'Stocks'), ('crypto', 'Crypto'), ('forex', 'Forex'), ('futures', 'Futures'), ('options', 'Options'), ('bonds', 'Bonds')], default=None, max_length=7)),
                ('trade_type', models.CharField(choices=[(None, 'Select Type'), ('DT', 'Day Trade'), ('ST', 'Swing'), ('LT', 'Long Term')], default=None, max_length=2)),
                ('symbol', models.CharField(max_length=15)),
                ('timeframe_day', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('timeframe_min', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('target', models.FloatField(blank=True, default=None, null=True)),
                ('stoploss', models.FloatField(blank=True, default=None, null=True)),
                ('expected_r', models.FloatField(blank=True, default=None, null=True)),
                ('setup', models.CharField(max_length=100)),
                ('mistakes', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
    ]
