# Generated by Django 4.1.4 on 2022-12-09 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0002_trade_owner_of_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='owner_of_trade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
    ]
