# Generated by Django 4.1.4 on 2022-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_avg_sell_price_trade_gross_return_trade_net_r_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='mistakes',
            field=models.CharField(default='Trade still open', max_length=200),
        ),
    ]
