# Generated by Django 4.1.4 on 2022-12-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_user_owners_trades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owners_trades',
        ),
    ]
