# Generated by Django 4.1.4 on 2022-12-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[(None, 'Select Action'), ('buy', 'buy'), ('sell', 'sell')], default=None, max_length=4)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='trades.trade')),
            ],
        ),
    ]
