# Generated by Django 4.1.4 on 2022-12-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[(None, 'Select Action'), ('buy', 'buy'), ('sell', 'sell')], default=None, max_length=4)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('commissions', models.FloatField(default=0)),
            ],
        ),
    ]
