# Generated by Django 4.1.5 on 2023-01-25 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('executions', '0001_initial'),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='execution',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='trades.trade'),
        ),
    ]
